# Generated by Django 4.0.3 on 2022-06-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
