# Generated by Django 4.0.3 on 2022-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='target',
            field=models.BooleanField(default=0),
        ),
    ]
